#!/usr/bin/env python3
"""Create one extra text note and select it together with existing voice note.

Precondition: current fixture note already contains a voice block generated by
recording in the same test.  The script creates another text note via the real
NewNoteButton, then Shift-selects two visible note rows so MultipleChoicesView
appears.  It does not modify the database directly.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
import time
import warnings
from collections.abc import Iterable

import gi

gi.require_version("Atspi", "2.0")
from gi.repository import Atspi  # noqa: E402

warnings.filterwarnings("ignore", category=DeprecationWarning)


def _children(node) -> Iterable:
    try:
        return [node.get_child_at_index(i) for i in range(node.get_child_count()) if node.get_child_at_index(i) is not None]
    except Exception:
        return []


def _walk(node):
    yield node
    for child in _children(node):
        yield from _walk(child)


def _name(node):
    try:
        return node.get_name() or ""
    except Exception:
        return ""


def _role(node):
    try:
        return node.get_role_name() or ""
    except Exception:
        return ""


def _ext(node):
    try:
        ext = node.get_extents(Atspi.CoordType.SCREEN)
    except Exception:
        return None
    if ext.width <= 0 or ext.height <= 0:
        return None
    return ext


def _find_app(app_name):
    desktop = Atspi.get_desktop(0)
    for app in _children(desktop):
        if _name(app) == app_name:
            return app
    raise RuntimeError(f"application not found: {app_name}")


def _find_by_name(root, name, visible=False):
    for node in _walk(root):
        if _name(node) == name and (not visible or _ext(node) is not None):
            return node
    raise RuntimeError(f"node not found: {name}")


def _wait_name(app_name, name, timeout, visible=False):
    deadline = time.time() + timeout
    last = None
    while time.time() < deadline:
        try:
            return _find_by_name(_find_app(app_name), name, visible=visible)
        except Exception as exc:
            last = exc
            time.sleep(0.15)
    raise RuntimeError(str(last) if last else f"timeout waiting {name}")


def _click(node, modifiers=None):
    ext = _ext(node)
    if ext is None:
        raise RuntimeError(f"node not visible: {_name(node)}")
    x = int(ext.x + ext.width / 2)
    y = int(ext.y + ext.height / 2)
    if modifiers:
        for key in modifiers:
            subprocess.run(["xdotool", "keydown", key], check=True)
    try:
        subprocess.run(["xdotool", "mousemove", str(x), str(y), "click", "1"], check=True)
    finally:
        if modifiers:
            for key in reversed(modifiers):
                subprocess.run(["xdotool", "keyup", key], check=True)
    time.sleep(0.35)


def _press(node):
    try:
        n = node.get_n_actions()
    except Exception:
        n = 0
    for i in range(max(n, 0)):
        try:
            if (node.get_action_name(i) or "").lower() in {"press", "click", "activate"}:
                node.do_action(i)
                time.sleep(0.4)
                return
        except Exception:
            continue
    if n > 0:
        node.do_action(0)
        time.sleep(0.4)
        return
    _click(node)


def _visible_note_items(app):
    list_view = _find_by_name(app, "NoteItemListView", visible=True)
    rows = []
    for node in _walk(list_view):
        if node is list_view:
            continue
        ext = _ext(node)
        if ext is None:
            continue
        name = _name(node)
        role = _role(node)
        if name and role in {"list item", "label", "panel"} and ext.width >= 40 and ext.height >= 20:
            rows.append((ext.y, node))
    out, seen = [], set()
    for y, node in sorted(rows, key=lambda t: t[0]):
        bucket = int(y / 8)
        if bucket in seen:
            continue
        seen.add(bucket)
        out.append(node)
    return out


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--app", default="deepin-voice-note")
    parser.add_argument("--timeout", type=float, default=10.0)
    args = parser.parse_args()
    try:
        Atspi.init()
    except Exception:
        pass

    _press(_wait_name(args.app, "NewNoteButton", args.timeout, visible=True))
    time.sleep(0.8)
    app = _find_app(args.app)
    items = _visible_note_items(app)
    if len(items) < 2:
        raise RuntimeError(f"need at least two visible note items, got {len(items)}")
    _click(items[0])
    _click(items[1], modifiers=["Shift_L"])
    _wait_name(args.app, "MultipleChoicesView", args.timeout, visible=True)
    # SaveVoiceButton must be enabled when at least one selected note has voice.
    btn = _wait_name(args.app, "SaveVoiceButton", args.timeout, visible=True)
    try:
        states = btn.get_state_set()
        if not (states.contains(Atspi.StateType.ENABLED) and states.contains(Atspi.StateType.SENSITIVE)):
            raise RuntimeError("SaveVoiceButton is visible but disabled")
    except AttributeError:
        pass
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"select_two_notes_for_multiselect_with_voice.py: {exc}", file=sys.stderr)
        raise SystemExit(1)
